# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Invoke Jenkins
      run: C:\Windows\System32\curl.exe -I -u admin:admin http://localhost:8080/job/TestHttpTrigger/build?token=${{ secrets.Jenkins_Token }}
  
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        repo: 'test'
      run: |
        echo "$GITHUB_CONTEXT"
        echo ${{ github.event.repository.created_at }}
          
    - name: Call HTTP
      uses: satak/webrequest-action@master
      with:
        url: https://smee.io/XcEp4bPuyjSAI4tZ
        method: POST
        payload: '{"name": "${{ github.event.repository.full_name }}"}'
       
